spring:
  profiles:
    active: s3Bucket
  application:
    # Application name
    name: Spring_boots
  datasource:
    # H2 Database configuration
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb
  h2:
    console:
      # H2 console settings - Access at http://localhost:8080/h2-console
      path: /h2-console
      enabled: 'true'
  devtools:
    restart:
      enabled: true
  jpa:
    # JPA Configuration
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 737842434086-u62st38eoe0bgottlt38iga0ink4aejh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: test@example.com
  secret_key: spring-boots

  secret: "zJf3VY8whF9OGkNhdMjf3Lx6jqFwG6kLcv3zjX3FSkQ=" ##32byte 이상
  token:
    refresh-expires: 604800000 # 7일
    access-expires: 900000 # 15분

admin:
  code: "springboots" #관리자코드
